version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '10:00'
      timezone: 'Europe/Berlin'
    ignore:
      - dependency-name: "@types/node"
        update-types: [ "version-update:semver-major" ]
